Repository CrowdStrike/Falcon-Toolkit, pull requests merged in 2023-01, with the labels that each got.

#22 🦺 Adds Device ID validation to the shell CLI
  falcon_toolkit/shell/cli.py
Labels: 🐛 bug

#23 📌 Version 3.0.2
  poetry.lock
  pyproject.toml
Labels: 🙌 enhancement, dependencies

#24 Fix minor typo on README
  README.md
Labels: 📝 documentation
